import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./provider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"className=" flex justify-center items-center">
      <AuthProvider>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-[95vw]`}
      >
        {children}
      </body>
      </AuthProvider>
      
    </html>
  );
}
